# ベースイメージを指定します
FROM node:18

# 作業ディレクトリを設定します
WORKDIR /app

# プロジェクトの残りのファイルをコピーします
COPY . .

# pnpmをインストールします
RUN npm install -g pnpm

# 依存関係をインストールします
RUN pnpm install

# ビルドを実行します
RUN pnpm -r run build

# Dockerコンテナが使用するポートを公開します
EXPOSE 3000

# Next.jsアプリケーションを起動します
CMD ["pnpm", "start"]
