# ベースイメージを指定します
FROM node:18

# 作業ディレクトリを設定します
WORKDIR /app

# プロジェクトの残りのファイルをコピーします
COPY . .

# 依存関係をインストールします
RUN npm install

# ビルドを実行します
RUN npm run build

# Dockerコンテナが使用するポートを公開します
EXPOSE 3000

# Next.jsアプリケーションを起動します
CMD ["npm", "start"]
